export const certificate = [
  {
    id: "1",
    name: "HTML, CSS, and Javascript for Web Developers",
    image: "HTML-CSS-JS-coursera",
    link: "https://www.coursera.org/account/accomplishments/verify/NZ5X59EAWLKW",
    organization: "Johns Hopkins University / coursera",
  },
  {
    id: "2",
    name: "HTML",
    image: "HTML-sololearn",
    link: "https://www.sololearn.com/certificates/CT-V3VCI3CW",
    organization: "sololearn",
  },
  {
    id: "3",
    name: "HTML & CSS",
    image: "HTML-CSS-clarusway",
    link: "https://c11n.clarusway.com/en/verify/88959462473458?ref",
    organization: "Clarusway",
  },
  {
    id: "4",
    name: "CSS",
    image: "CSS-sololearn",
    link: "https://www.sololearn.com/certificates/CT-LVRNSZV5",
    organization: "sololearn",
  },
  {
    id: "5",
    name: "JavaScript",
    image: "JavaScript-clarusway",
    link: "https://d34lllqo5jm5il.cloudfront.net/en/verify/14011979731638?ref",
    organization: "Clarusway",
  },
  {
    id: "6",
    name: "JavaScript",
    image: "JavaScript-sololearn",
    link: "https://www.sololearn.com/certificates/CT-DBICX4OV",
    organization: "sololearn",
  },
  {
    id: "7",
    name: "Responsive Web Design",
    image: "responsive-sololearn",
    link: "https://www.sololearn.com/certificates/CT-DQ3QK47Y",
    organization: "sololearn",
  },
  {
    id: "8",
    name: "React",
    image: "React-clarusway",
    link: "https://d34lllqo5jm5il.cloudfront.net/en/verify/46919411594228?ref",
    organization: "Clarusway",
  },
  {
    id: "9",
    name: "React + Redux",
    image: "React-redux-sololearn",
    link: "https://www.sololearn.com/certificates/CT-KFBCE8CQ",
    organization: "sololearn",
  },
  {
    id: "10",
    name: "Design and Develop a Website using Figma and CSS",
    image: "figma-coursera",
    link: "https://www.coursera.org/account/accomplishments/verify/M7N5HF9J4YUH",
    organization: "coursera",
  },
  {
    id: "11",
    name: "Frontend Developer",
    image: "Frontend-Developer-clarusway",
    link: "https://d34lllqo5jm5il.cloudfront.net/en/verify/30815763018219?ref",
    organization: "Clarusway",
  },
  {
    id: "12",
    name: "Python for Beginners",
    image: "python-sololearn",
    link: "https://www.sololearn.com/certificates/CT-9YGKRKZE",
    organization: "sololearn",
  },
  {
    id: "13",
    name: "Game Development with JS",
    image: "game-development-with-JS",
    link: "https://www.sololearn.com/certificates/CT-EYLZ1B1B",
    organization: "sololearn",
  },
];
